name: Build package
on:
  push:
    branches:
      - section05


jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.9
        cache: true
    - name: Install tools
      run: pdm install

    - name: Build package
      run: pdm build

    - name: Upload Wheel
      uses: actions/upload-artifact@v4
      with:
        name: project_build
        path: dist/*.whl

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . -t stug101/yustashw5:latest

    - name: Push the Docker image
      run: docker push stug101/yustashw5:latest